services:
  api:
    build: .
    ports: ["3000:3000"]
    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/tasks
      SUPABASE_URL: https://cflenjvmqvxuixqlniyk.supabase.co
      SUPABASE_KEY: sb_publishable_eP0ij4dVjtW6czzNyaIOyw_RbzDV7KR
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tasks
    volumes: [taskdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  taskdata:
